export const products = [
  {
    id: 1,
    title: "Wireless Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI.",
    price: 25.99,
    tags: ["electronics", "accessories", "wireless"],
    stock: 150,
    category: "Electronics",
    viewCount: 1200,
  },
  {
    id: 2,
    title: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with deep bass.",
    price: 45.99,
    tags: ["electronics", "audio", "portable"],
    stock: 80,
    category: "Electronics",
    viewCount: 950,
  },
  {
    id: 3,
    title: "Running Shoes",
    description: "Lightweight running shoes for daily workouts.",
    price: 60.0,
    tags: ["sports", "footwear", "running"],
    stock: 200,
    category: "Sportswear",
    viewCount: 700,
  },
  {
    id: 4,
    title: "Gaming Keyboard",
    description: "Mechanical keyboard with RGB lighting.",
    price: 75.5,
    tags: ["electronics", "gaming", "keyboard"],
    stock: 50,
    category: "Electronics",
    viewCount: 1500,
  },
  {
    id: 5,
    title: "Smartwatch",
    description: "Feature-packed smartwatch with fitness tracking.",
    price: 120.0,
    tags: ["electronics", "wearables", "fitness"],
    stock: 100,
    category: "Electronics",
    viewCount: 1800,
  },
  {
    id: 6,
    title: "Backpack",
    description: "Durable backpack with multiple compartments.",
    price: 35.0,
    tags: ["accessories", "travel", "bags"],
    stock: 300,
    category: "Accessories",
    viewCount: 600,
  },
  {
    id: 7,
    title: "Desk Lamp",
    description: "LED desk lamp with adjustable brightness.",
    price: 20.0,
    tags: ["home", "lighting", "LED"],
    stock: 120,
    category: "Home & Living",
    viewCount: 400,
  },
  {
    id: 8,
    title: "Yoga Mat",
    description: "Non-slip yoga mat for all types of exercises.",
    price: 18.5,
    tags: ["fitness", "yoga", "exercise"],
    stock: 250,
    category: "Sportswear",
    viewCount: 500,
  },
];
